name: Run sentiment scrapers every hour

on:
  schedule:
    - cron: '0 * * * *'  # toutes les heures
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le repo
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances Python
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Installer les navigateurs Playwright
        run: |
          python -m playwright install

      - name: Installer xvfb et exécuter les scripts
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          xvfb-run python3 corr_matrix_scraper_playwright.py && python3 myfxbook_scraper.
